name: "CodeTime - Readme"
author: "xafec"
description: "Add a CodeTime Coding Activity graph in your Readme"

inputs:
  USERNAME:
    description: "Your CodeTime username"
    default: ${{ github.repository_owner }}

  GH_TOKEN:
    description: "Your GitHub token"
    required: true
    default: ${{ github.token }}

  CODETIME_COOKIE_KEY:
    description: "Your CodeTime cookie key"
    required: true

runs:
  using: docker
  image: Dockerfile

branding:
  icon: "activity"
  color: "blue"
